# Generated by Django 5.1.1 on 2024-11-28 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TPedidos_app', '0002_rename_tpedidos_tpedido'),
        ('TProductos_app', '0002_rename_tproductos_tproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDetallePedido',
            fields=[
                ('detalleid', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('notas', models.TextField()),
                ('pedidoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TPedidos_app.tpedido')),
                ('productoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TProductos_app.tproducto')),
            ],
        ),
    ]
